name: step001
# on: [push, fork, workflow_dispatch]
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install dep
        run: npm ci
      # - name: lint
      #   run: npm run lint
      - name: test
        run: npm run test
  job02:
    needs: job01
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install dep
        run: npm ci
      - name: build
        run: npm run build
  job03:
    needs: job02
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploy to ECR"