name: step001
# on: [push, fork, workflow_dispatch]
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo "${{ github.repository }}"