name: step001
# on: [push, fork, workflow_dispatch]
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install dep
        run: npm ci
      # - name: lint
      #   run: npm run lint
      - name: test
        run: npm run test
  job02:
    needs: job01
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install dep
        run: npm ci
      - name: build
        run: npm run build
      - name: publish js filename
        run: find dist/assets/*.js -type f -execdir echo '{}' ';'
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
            package.json
  job03:
    needs: job02
    runs-on: ubuntu-latest
    steps:
      - name: get artifacts
        uses: actions/download-artifact@v4 
        with:
          name: dist-files
      - name: Display structure of downloaded files
        run: ls -R
      - name: deploy
        run: echo "deploy to ECR"